x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME}
  env_file: .env
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/files:/opt/airflow/files    
    - ./airflow/logs:/opt/airflow/logs      
    - ./airflow/config:/opt/airflow/config  
    - ./airflow/plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  depends_on:
    &airflow-common-depends-on
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    env_file: .env
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/pg_files:/files
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-airflow} -d ${POSTGRES_DB:-airflow}"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - lake
    restart: always

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    container_name: airflow-init
    command: >
      -c "
      airflow db migrate &&
      airflow users create --username ${AIRFLOW_WWM_USER_USERNAME:-airflow} --password ${AIRFLOW_WWM_USER_PASSWORD:-airflow} --firstname Allahverdi --lastname Hajiyev --role Admin --email admin@local
      "
    networks:
      - lake
    user: "0:0"
    volumes:
      - ./airflow:/sources
    restart: "no"

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    container_name: airflow-webserver
    networks:
      - lake
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    container_name: airflow-scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - lake
    depends_on:
      <<: *airflow-common-depends-on
      airflow-init:
        condition: service_completed_successfully

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    command: server /data --console-address ":9001"
    env_file: .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio:/data
    networks:
      - lake
    restart: always

volumes:
  airflow:
  minio:
  pgdata:
  pg_files:

networks:
  lake:
    driver: bridge